version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/web/'
    open-pull-requests-limit: 20
    schedule:
      interval: 'weekly'
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
  - package-ecosystem: "github-actions"
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: "docker"
    directory: "/web"
    schedule:
      interval: "weekly"
