version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/web/'
    schedule:
      interval: 'daily'
    groups:
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'daily'
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
