services:
  directus:
    image: directus/directus:10.11.0
    networks:
      - custom-app-network
    ports:
      - 8055:8055
    volumes:
      - ./directus/database:/directus/database
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"

  sveltekit:
    build: ./sveltekit
    networks:
      - custom-app-network
    ports:
      - "5173:5173"
    volumes:
      - ./sveltekit:/app
      - /app/node_modules
    environment:
      NODE_ENV: "development"
      PUBLIC_APIURL: "http://localhost:5173/api"
      PRIVATE_APIURL: "http://directus:8055"
    command: npm run dev -- --host

networks:
  custom-app-network: