services:

  database:
    image: postgis/postgis:16-master
    ports:
      - 5432:5432
    volumes:
      - ./directus/postgres:/var/lib/postgresql/data
    env_file: ".env"
    networks:
      - custom-app-network

  directus:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/database:/directus/database
    depends_on:
      - database
    env_file: ".env"
    networks:
      - custom-app-network

  sveltekit:
    image: ghcr.io/h3nkl3r/lace:main
    networks:
      - custom-app-network
    ports:
      - "3000:3000"
    env_file: ".env"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /var/lib/rbg-cert:/var/lib/rbg-cert:ro
      - /usr/local/cert.d/nginx:/usr/local/cert.d/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sveltekit
    networks:
      - custom-app-network

networks:
  custom-app-network: