services:

  database:
    image: postgis/postgis:16-master
    ports:
      - 5432:5432
    volumes:
      - ./cms/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    networks:
      - custom-app-network

  cms:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./cms/uploads:/directus/uploads
      - ./cms/extensions:/directus/extensions
      - ./cms/database:/directus/database
    depends_on:
      - database
    environment:
      SECRET: "4gexm6-E_uoqgidop994UUNnM7iQu.Jde3WPJuJW-Qk_-qA*hLmML4@z46Z2qeCN"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "http://localhost/"
    networks:
      - custom-app-network

  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    networks:
      - custom-app-network
    ports:
      - "3000:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      NODE_ENV: "development"
      PUBLIC_WEB_URL: "https://localhost"
      PUBLIC_CMS_URL: "https://localhost/cms"
      PRIVATE_APIURL: "http://cms:8055"
      PREVIEW_COOKIE_NAME: "__preview_mode"
      PREVIEW_SECRET: "53lt3k1t"
      PRIVATE_KEY: "hallo"
      PUBLIC_KEY: "hallo"
      DIRECTUS_TOKEN: "gyVklUY5Ezrs2vRvfki21cHGdKjUDZaU"
    command: npm run dev -- --host

  nginx:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/nginx.local.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - custom-app-network

networks:
  custom-app-network:
    driver: bridge