services:

  database:
    image: postgis/postgis:16-master
    ports:
      - 5432:5432
    volumes:
      - ./directus/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "directus"
      POSTGRES_PASSWORD: "directus"
      POSTGRES_DB: "directus"
    networks:
      - custom-app-network

  directus:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/database:/directus/database
    depends_on:
      - database
    environment:
      KEY: "replace-with-random-value"
      SECRET: "replace-with-random-value"
      DB_CLIENT: "pg"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_DATABASE: "directus"
      DB_USER: "directus"
      DB_PASSWORD: "directus"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "d1r3ctu5"
      CONTENT_SECURITY_POLICY_DIRECTIVES__FRAME_SRC: "http://localhost/"
    networks:
      - custom-app-network

  sveltekit:
    build:
      context: ./sveltekit
      dockerfile: Dockerfile.dev
    networks:
      - custom-app-network
    ports:
      - "3000:5173"
    volumes:
      - ./sveltekit:/app
      - /app/node_modules
    environment:
      NODE_ENV: "development"
      PUBLIC_URL: "https://localhost"
      PRIVATE_APIURL: "http://directus:8055"
      PREVIEW_COOKIE_NAME: "__preview_mode"
      PREVIEW_SECRET: "53lt3k1t"
      PRIVATE_KEY: "hallo"
      PUBLIC_KEY: "hallo"
      DIRECTUS_TOKEN: "gyVklUY5Ezrs2vRvfki21cHGdKjUDZaU"
    command: npm run dev -- --host

  nginx:
    image: nginx:latest
    volumes:
      - ./sveltekit/nginx.local.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - sveltekit
    networks:
      - custom-app-network

networks:
  custom-app-network: