services:

  database:
    image: postgis/postgis:16-master
    ports:
      - 5432:5432
    volumes:
      - ./directus/postgres:/var/lib/postgresql/data
    env_file: ".env"
    networks:
      - custom-app-network

  directus:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./directus/uploads:/directus/uploads
      - ./directus/extensions:/directus/extensions
      - ./directus/database:/directus/database
    depends_on:
      - database
    env_file: ".env"
    networks:
      - custom-app-network

  sveltekit:
    build:
      context: ./sveltekit
    networks:
      - custom-app-network
    ports:
      - "80:3000"
    env_file: ".env"

networks:
  custom-app-network: