services:

  database:
    image: postgis/postgis:16-master
    ports:
      - 5432:5432
    volumes:
      - ./cms/postgres:/var/lib/postgresql/data
    env_file: ".env"
    networks:
      - custom-app-network

  cms:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./cms/uploads:/directus/uploads
      - ./cms/extensions:/directus/extensions
      - ./cms/database:/directus/database
    depends_on:
      - database
    env_file: ".env"
    networks:
      - custom-app-network

  web:
    build:
      context: web
    networks:
      - custom-app-network
    ports:
      - "3000:5173"
    env_file: ".env"

  nginx:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/nginx.local.conf:/etc/nginx/nginx.conf
      - ./reverse-proxy/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    networks:
      - custom-app-network

networks:
  custom-app-network: